### ISSUE TITLE
When will the code be released

### ISSUE THREAD

**Issue by weidafeng** [ChungYi347/Interactive-Multi-Class-Tiny-Object-Detection#1]
Dear authors, the work presented in your paper is very impressive, and when will the code be released?
Thanks in advance.

**Comment by ChungYi347** [comment]
Thank you for your interest in our research!
We are refactoring our code and will upload our code as soon as possible.
We hope to upload the code before end of CVPR'22 conference.
Sorry for that.

**Comment by swook** [comment]
Hullo @weidafeng,

Thanks for your interest in our work and accompanying code.

Due to the reviewing process that is internal to our company, the code release is unfortunately delayed (we will need up to a month more). We ask for your understanding.

We will update you via this issue as soon as the code is available!

Thanks!
